### ISSUE TITLE
'ldns/ldns.h' file not found

### ISSUE THREAD

**Issue by phillip-burger-sculpturearts** [hrbrmstr/resolv#1]
Any suggestions on how to navigate through the file not found error shown below the environment info?

Environment:

> version
>                _  
> platform       x86_64-apple-darwin13.1.0  
> arch           x86_64  
> os             darwin13.1.0  
> system         x86_64, darwin13.1.0  
> status  
> major          3  
> minor          1.1  
> year           2014  
> month          07  
> day            10  
> svn rev        66115  
> language       R  
> version.string R version 3.1.1 (2014-07-10)
> nickname       Sock it to Me    

Error: 

> install_github("hrbrmstr/resolv")
> Installing github repo resolv/master from hrbrmstr
> Downloading master.zip from https://github.com/hrbrmstr/resolv/archive/master.zip
> Installing package from /var/folders/zf/cgqgtb_96j7113skpkr0y5k80000gq/T//Rtmpq6enzY/master.zip
> arguments 'minimized' and 'invisible' are for Windows only
> Installing resolv
> '/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
>   '/private/var/folders/zf/cgqgtb_96j7113skpkr0y5k80000gq/T/Rtmpq6enzY/devtools9e6c68e0656e/resolv-master'  \
>   --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 
- installing _source_ package 'resolv' ...
  *\* libs
  clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
  clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c rcpp_resolv.cpp -o rcpp_resolv.o
  rcpp_resolv.cpp:19:10: fatal error: 'ldns/ldns.h' file not found
  #include <ldns/ldns.h>
       ^
  1 error generated.
  make: **\* [rcpp_resolv.o] Error 1
  ERROR: compilation failed for package 'resolv'
- removing '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/resolv'
  Error: Command failed (1)

**Comment by hrbrmstr** [comment]
How did you install the `ldns` library? via `brew install ldns`? macports also [has the library](http://www.macports.org/ports.php?by=library&substr=ldns) in their ports directory. You need that installed (as the post indicated) for `resolv` to work.

**Comment by phillip-burger-sculpturearts** [comment]
Got it. Executing brew install ldns first does resolve the error I encountered.
